### ISSUE TITLE
Not able to import in latest version of deno

### ISSUE THREAD

**Issue by justinmchase** [cloudydeno/deno-kubernetes_apis#18]
```
import { CoreV1Api } from "@cloudydeno/kubernetes-apis";
```

Gives an error:
![image](https://github.com/user-attachments/assets/708d4853-e350-491b-8d0d-7df0d4dfeea6)

**Comment by justinmchase** [comment]
Oh wait I see it just doesn't export `"."` which I guess is unusual but not a problem technically. If I just add `/core/v1` onto the end of the import it works fine.

I guess the `"."` module is just useful for getting started, for UX purposes? Anyway, not actually a bug.

**Comment by danopia** [comment]
Hey Justin,
I indeed kept the same import scheme as /x/ when setting up this JSR package. So you would continue importing specific modules by path just like before.

I originally made the decision to not have a default export because of the relatively large amount of code generated by the entire Kubernetes API surface. The default import would load in nearly a megabyte of generated code, so by making you select the APIs you need, your dependencies can download and parse a bit faster.

Since there's no JSR example in the README, I can understand why this wasn't clear. I'll get one added for the next tag. Thanks for writing in.
